version: '3'
services:
    mongo:
        image: mongo:latest
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 
        ports:
            - "27017:27017"
        volumes:
            - ./docker/mongo:/data/db
    database:
        image: mysql:latest
        container_name: database
        command: "--default-authentication-plugin=mysql_native_password"
        environment:
            MYSQL_ROOT_PASSWORD: dfe4da18
            MYSQL_DATABASE: lanchonete
            MYSQL_USER: dev-norton
            MYSQL_PASSWORD: admin
        volumes:
            - ./database:/docker-entrypoint-initdb.d/
            - ./docker/mysql:/var/lib/mysql
        ports:
            - "3306:3306"